# Generated by Django 5.0.6 on 2026-07-01 13:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_account_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "supplier",
            },
        ),
        migrations.CreateModel(
            name="TargetTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("geojson", "GeoJSON"),
                            ("csv", "CSV"),
                            ("xml", "XML"),
                            ("xlsx", "XLSX"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="transformation.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "target_template",
                "unique_together": {("supplier", "format")},
            },
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_field", models.CharField(max_length=255)),
                ("target_field", models.CharField(max_length=255)),
                ("handler_method", models.CharField(default="direct", max_length=64)),
                ("handler_data", models.JSONField(blank=True, default=dict, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="transformation.targettemplate",
                    ),
                ),
            ],
            options={
                "db_table": "field_mapping",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TransformationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("format", models.CharField(max_length=16)),
                ("s3_path", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PARTIAL", "Partial"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("total_chunks", models.IntegerField(default=0)),
                ("processed_chunks", models.IntegerField(default=0)),
                ("failed_chunks", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="transformation.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "transformation_job",
            },
        ),
    ]
