# Generated by Django 5.0.6 on 2026-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transformationjob",
            name="output_s3_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
