# Generated by Django 5.0.6 on 2026-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0002_output_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
