# Generated by Django 5.0.6 on 2026-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0003_started_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="targettemplate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="targettemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="transformationjob",
            name="template_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="targettemplate",
            unique_together={("supplier", "format", "version")},
        ),
    ]
