# Generated by Django 5.0.6 on 2026-07-03 14:59

from django.db import migrations, models


def mark_existing_templates_published(apps, schema_editor):
    """Pre-existing templates represent mappings already live in production —
    only templates created after this migration should start life as DRAFT."""
    TargetTemplate = apps.get_model("transformation", "TargetTemplate")
    TargetTemplate.objects.update(status="PUBLISHED")


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0006_source_field_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="targettemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("DEPRECATED", "Deprecated"),
                ],
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            mark_existing_templates_published, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="allowed_values",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Non-empty list = enum; value must be in list.",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="date_format",
            field=models.CharField(
                blank=True,
                default="",
                help_text="strptime format; blank = ISO 8601.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="default_value",
            field=models.JSONField(
                blank=True,
                help_text="Used when field is absent and not required.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="name",
            field=models.CharField(
                help_text="Field name as it appears in the source data.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="nullable",
            field=models.BooleanField(
                default=False,
                help_text="Value may be null/empty even when field is present.",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="required",
            field=models.BooleanField(
                default=True, help_text="Item is rejected if this field is absent."
            ),
        ),
    ]
