# Generated by Django 5.0.6 on 2026-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0008_order_counters"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transformationjob",
            index=models.Index(
                fields=["supplier", "-created_at"], name="job_supplier_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transformationjob",
            index=models.Index(fields=["status"], name="job_status_idx"),
        ),
    ]
