# Generated by Django 5.0.6 on 2026-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0010_template_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcefielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("number", "Number (float)"),
                    ("integer", "Integer"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("geojson", "GeoJSON geometry"),
                    ("object", "Nested object"),
                    ("email", "Email"),
                    ("url", "URL"),
                ],
                default="string",
                max_length=16,
            ),
        ),
    ]
