# Generated by Django 5.0.6 on 2026-07-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0012_rename_storage_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sourcefielddefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sourcefielddefinition",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when this field describes a key nested inside an 'object'-type field. The parent must itself be field_type=object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="transformation.sourcefielddefinition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sourcefielddefinition",
            unique_together={("template", "parent", "name")},
        ),
    ]
