# Generated by Django 5.0.6 on 2026-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0013_alter_sourcefielddefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationjob",
            name="chunk_size",
            field=models.IntegerField(default=5000),
        ),
    ]
