# Generated by Django 5.0.6 on 2026-07-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0014_transformationjob_chunk_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transformationjob",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="transformationjob",
            name="skipped_items",
            field=models.IntegerField(default=0),
        ),
    ]
