# Generated by Django 5.0.6 on 2026-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0015_remove_transformationjob_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="sheet_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
