# Generated by Django 5.0.6 on 2026-07-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0016_fieldmapping_sheet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationjob",
            name="total_items",
            field=models.IntegerField(default=0),
        ),
    ]
