# Generated by Django 5.0.6 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="codename",
            field=models.CharField(
                help_text="e.g. mapping.edit", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplierauth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplierauth",
            name="password",
            field=models.CharField(
                help_text="Django PBKDF2 hash via make_password.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="supplierauth",
            name="supplier_id",
            field=models.IntegerField(
                db_index=True,
                help_text="Soft FK to transformation.Supplier — same DB, no DB constraint.",
            ),
        ),
        migrations.AlterField(
            model_name="suppliergroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suppliergroup",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Rights granted to members of this group.",
                related_name="groups",
                to="supplier_auth.permission",
            ),
        ),
    ]
