# Generated by Django 5.0.6 on 2026-07-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier_auth",
            "0002_alter_permission_codename_alter_permission_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformationSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("supplier_account_id", models.IntegerField()),
            ],
            options={
                "db_table": "supplier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierAuthToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "supplier_auth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="supplier_auth.supplierauth",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_auth_token",
            },
        ),
    ]
